# Generated by Django 5.2.8 on 2025-11-22 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Süper Admin'), ('admin', 'Admin'), ('editor', 'Editör'), ('viewer', 'Görüntüleyici')], max_length=50, unique=True, verbose_name='Rol Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Admin Rolü',
                'verbose_name_plural': 'Admin Rolleri',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.adminrole', verbose_name='Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Admin Kullanıcı',
                'verbose_name_plural': 'Admin Kullanıcılar',
            },
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view_dashboard', 'Dashboard Görüntüleme'), ('manage_campaigns', 'Kampanya Yönetimi'), ('manage_products', 'Ürün Yönetimi'), ('manage_orders', 'Sipariş Yönetimi'), ('view_reports', 'Rapor Görüntüleme'), ('export_data', 'Veri Export'), ('manage_users', 'Kullanıcı Yönetimi'), ('manage_settings', 'Ayar Yönetimi')], max_length=50, verbose_name='İzin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='admin_panel.adminrole', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Admin İzni',
                'verbose_name_plural': 'Admin İzinleri',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
