# Generated by Django 5.2.8 on 2025-11-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Gumbuz Butik', max_length=255, verbose_name='Mağaza Adı')),
                ('store_slogan', models.CharField(blank=True, max_length=255, verbose_name='Mağaza Sloganı')),
                ('store_description', models.TextField(blank=True, verbose_name='Mağaza Açıklaması')),
                ('store_logo', models.ImageField(blank=True, upload_to='settings/', verbose_name='Mağaza Logosu')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp Numarası')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram Profili')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook Sayfası')),
                ('gtm_id', models.CharField(blank=True, max_length=50, verbose_name='Google Tag Manager ID')),
                ('ga4_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics 4 ID')),
                ('pixel_id', models.CharField(blank=True, max_length=50, verbose_name='Meta Pixel ID')),
                ('hotjar_id', models.CharField(blank=True, max_length=50, verbose_name='Hotjar ID')),
                ('contentsquare_id', models.CharField(blank=True, max_length=50, verbose_name='ContentSquare ID')),
                ('onesignal_app_id', models.CharField(blank=True, max_length=100, verbose_name='OneSignal App ID')),
                ('facebook_domain_verification', models.CharField(blank=True, max_length=100, verbose_name='Facebook Domain Verification')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
