# Generated by Django 5.2.8 on 2025-11-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='rate_limit_count',
            field=models.PositiveIntegerField(default=5, verbose_name='Rate Limit (Adet)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rate_limit_period',
            field=models.PositiveIntegerField(default=600, verbose_name='Rate Limit Süresi (Saniye)'),
        ),
    ]
