# Generated by Django 5.2.8 on 2025-12-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='info_note_content',
            field=models.TextField(default='Siparişlerinizi 14 gün içinde iade etme hakkınız bulunmaktadır.', verbose_name='Bilgi Notu İçeriği'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='info_note_title',
            field=models.CharField(default='Kapıda Ödeme Sistemi & İade Hakkı', max_length=255, verbose_name='Bilgi Notu Başlığı'),
        ),
    ]
