# Generated by Django 5.2.8 on 2025-12-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_sitesettings_info_note_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme_accent_color',
            field=models.CharField(default='#FF6B6B', max_length=20, verbose_name='Vurgu Rengi (Accent)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_primary_color',
            field=models.CharField(default='#E91E63', max_length=20, verbose_name='Ana Renk (Primary)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_secondary_color',
            field=models.CharField(default='#9C27B0', max_length=20, verbose_name='İkincil Renk (Secondary)'),
        ),
    ]
