# Generated by Django 5.2.8 on 2025-11-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('products', '0002_alter_product_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Kampanya', 'verbose_name_plural': 'Kampanyalar'},
        ),
        migrations.AlterModelOptions(
            name='campaignproduct',
            options={'ordering': ['sort_order'], 'verbose_name': 'Kampanya Ürünü', 'verbose_name_plural': 'Kampanya Ürünleri'},
        ),
        migrations.AlterModelOptions(
            name='campaignsize',
            options={'verbose_name': 'Kampanya Bedeni', 'verbose_name_plural': 'Kampanya Bedenleri'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='Kampanya Açıklaması'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='banner_image',
            field=models.ImageField(upload_to='campaigns/', verbose_name='Banner Görseli'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cod_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kapıda Ödeme Ücreti'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cod_price_discounted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='İndirimli Kapıda Ödeme Ücreti'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='min_quantity',
            field=models.IntegerField(default=3, verbose_name='Minimum Adet'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='products',
            field=models.ManyToManyField(related_name='campaigns', through='campaigns.CampaignProduct', to='products.product', verbose_name='Ürünler'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kargo Ücreti'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='shipping_price_discounted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='İndirimli Kargo Ücreti'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Kısa Ad (Slug)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Kampanya Başlığı'),
        ),
        migrations.AlterField(
            model_name='campaignproduct',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign', verbose_name='Kampanya'),
        ),
        migrations.AlterField(
            model_name='campaignproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='campaignproduct',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='campaignsize',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='campaigns.campaign', verbose_name='Kampanya'),
        ),
        migrations.AlterField(
            model_name='campaignsize',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='campaignsize',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Beden Etiketi'),
        ),
    ]
