# Generated by Django 5.2.8 on 2025-11-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_options_alter_campaignproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Beden İsmi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (Kod)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Beden Seçeneği',
                'verbose_name_plural': 'Beden Seçenekleri',
            },
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='products',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/', verbose_name='Banner Görseli'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cod_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kapıda Ödeme Bedeli'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cod_price_discounted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirimli Kapıda Ödeme Bedeli'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Minimum Adet'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='campaignproduct',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, to='campaigns.sizeoption', verbose_name='Tanımlı Bedenler'),
        ),
        migrations.DeleteModel(
            name='CampaignSize',
        ),
    ]
