# Generated by Django 5.2.8 on 2025-11-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cod_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Kapıda Ödeme Bedeli'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cod_price_discounted',
            field=models.DecimalField(decimal_places=2, default=85, max_digits=10, verbose_name='İndirimli Kapıda Ödeme Bedeli'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Kargo Ücreti'),
        ),
    ]
