# Generated by Django 5.2.8 on 2025-11-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_cod_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Sıra'),
        ),
    ]
