# Generated by Django 5.2.8 on 2025-11-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='order',
        ),
    ]
