# Generated by Django 5.2.8 on 2025-11-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=255, unique=True, verbose_name='Eski Slug')),
                ('old_title', models.CharField(blank=True, max_length=255, verbose_name='Eski Başlık')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Manuel Eklendi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='campaigns.campaign', verbose_name='Hedef Kampanya')),
            ],
            options={
                'verbose_name': 'Kampanya Yönlendirmesi',
                'verbose_name_plural': 'Kampanya Yönlendirmeleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
