# Generated by Django 5.2.8 on 2025-11-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_alter_product_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': 'Siparişler'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Sipariş Ürünü', 'verbose_name_plural': 'Sipariş Ürünleri'},
        ),
        migrations.AlterField(
            model_name='order',
            name='campaign_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kampanya Fiyatı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_firm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Firması'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kargo Ücreti'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kapıda Ödeme Bedeli'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Müşteri Adı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(max_length=100, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_address',
            field=models.TextField(verbose_name='Tam Adres'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Tutar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Takip Kodu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Sipariş'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Adet'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Seçilen Beden'),
        ),
    ]
