# Generated by Django 5.2.8 on 2025-11-21 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_options_alter_campaignproduct_options_and_more'),
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign', verbose_name='Satın Alınan Kampanya'),
        ),
        migrations.AddField(
            model_name='order',
            name='cargo_barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Barkod'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni Sipariş'), ('processing', 'İşleme Alındı'), ('shipped', 'Kargolandı'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal'), ('return', 'İade')], default='new', max_length=20, verbose_name='Durum'),
        ),
    ]
