# Generated by Django 5.2.8 on 2025-11-22 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('orders', '0003_order_campaign_order_cargo_barcode_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='addresses.city', verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='order',
            name='district_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='addresses.district', verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='order',
            name='neighborhood_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='addresses.neighborhood', verbose_name='Mahalle'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='İlçe'),
        ),
    ]
