# Generated by Django 5.2.8 on 2025-11-22 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_order'),
        ('orders', '0004_order_city_fk_order_district_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='campaigns.campaign', verbose_name='Satın Alınan Kampanya'),
        ),
    ]
