# Generated by Django 5.2.8 on 2025-11-22 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_remove_campaign_order'),
        ('orders', '0005_alter_order_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign', verbose_name='Satın Alınan Kampanya'),
        ),
    ]
