# Generated by Django 5.2.8 on 2025-11-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ürün Adı (Snapshot)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU (Snapshot)'),
        ),
    ]
