# Generated by Django 5.2.8 on 2025-11-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_product_name_orderitem_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama (Snapshot)'),
        ),
    ]
