# Generated by Django 5.2.8 on 2025-11-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Görsel URL (Snapshot)'),
        ),
    ]
