# Generated by Django 5.2.8 on 2025-11-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='campaign_image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kampanya Görsel URL (Snapshot)'),
        ),
        migrations.AddField(
            model_name='order',
            name='campaign_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Kampanya Slug (Snapshot)'),
        ),
        migrations.AddField(
            model_name='order',
            name='campaign_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kampanya Başlığı (Snapshot)'),
        ),
    ]
