# Generated by Django 5.2.8 on 2025-11-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_campaign_image_url_order_campaign_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_size_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Beden Açıklaması'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Beden İsmi'),
        ),
    ]
