# Generated by Django 5.2.8 on 2025-12-02 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_selected_size_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Durum')),
                ('reason', models.CharField(choices=[('size_mismatch', 'Beden Uymadı'), ('defective', 'Kusurlu Ürün'), ('wrong_item', 'Yanlış Ürün'), ('changed_mind', 'Vazgeçtim'), ('other', 'Diğer')], max_length=50, verbose_name='İade Nedeni')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN Numarası')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Yönetici Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'İade Talebi',
                'verbose_name_plural': 'İade Talepleri',
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='İade Adedi')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem', verbose_name='Sipariş Ürünü')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.returnrequest', verbose_name='İade Talebi')),
            ],
            options={
                'verbose_name': 'İade Ürünü',
                'verbose_name_plural': 'İade Ürünleri',
            },
        ),
    ]
